block.settings.burda_cmp_sourcepoint_open_privacy_manager:*:
  type: block_settings
  label: 'Open privacy manager block (Sourcepoint)'
  mapping:
    link_text:
      type: label
      label: 'Link text'

burda_cmp.settings:
  type: config_object
  label: 'Consent management platform settings'
  mapping:
    sourcepoint_script_url:
      type: string
      label: 'Sourcepoint script URL'
